"""empty message

Revision ID: 1d3a0c965479
Revises: 2b42580c329a
Create Date: 2023-01-27 18:10:43.489915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3a0c965479'
down_revision = '2b42580c329a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
